POST http://localhost:8080/polls
Content-Type: application/json

{
  "title": "Qual o melhor framework Node.js?",
  "options": [
    "Express",
    "Koa",
    "Nest",
    "Hapi",
    "Adonis"
  ]
}

###
GET http://localhost:8080/polls/5986533f-c8d7-4965-a976-94b5db04c5c6
Content-Type: application/json

###
GET http://localhost:8080/polls/5986533f-c8d7-4965-a976-94b5db04c5c6/results 
Content-Type: application/json


###
POST http://localhost:8080/polls/5986533f-c8d7-4965-a976-94b5db04c5c6/votes
Content-Type: application/json

{
  "pollOptionId": "f574f1a8-6d50-428e-8d8e-4f2301ec22cf"
}